### ISSUE TITLE
Why does data come from API with most recent timestamp first in array?

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/smartthings.htm.bridge#17]
I noticed that the values for a sensor come in the form of an array, with the most recent timestamp being the first item in the array. I would expect this to be the opposite.

This also means that we have to reverse the array in the client in order to render in the chart, as DyGraphs expects the most recent timestamp to be the last item in the array.

Questions:

Am I doing it wrong somehow?
or
Is there a reason for this that I am unaware of? Something having to do with InfluxDB?

**Comment by jefffohl** [comment]
Oh, I think I see why now. It would appear there is a bug in the `getSensorData()` function in `influxclient.py`:

This is the current code:

```python
  query = "SELECT * FROM " + measurement \
        + " WHERE component = '" + component + "'"
  if since is not None:
    query += " AND time > {0}s".format(since)
  if limit is not None:
    query += " GROUP BY * ORDER BY time DESC LIMIT {0}".format(limit)
  response = client.query(query)
```

shouldn't it be:

```python
  query = "SELECT * FROM " + measurement \
        + " WHERE component = '" + component + "'"
  if since is not None:
    query += " AND time > {0}s".format(since)
  query += " GROUP BY * ORDER BY time DESC"
  if limit is not None:
     query += "LIMIT {0}".format(limit)
  response = client.query(query)
```

**Comment by jefffohl** [comment]
That is, you get different results depending on if you include a `limit` URL parameter or not. If you don't include one, you get the results in a different order.

**Comment by jefffohl** [comment]
I can submit a fix for this in my next PR

**Comment by rhyolight** [comment]
Good catch.
