### ISSUE TITLE
Add checkboxes on each chart to show/hide anomaly lines

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/smartthings.htm.bridge#3]
For both anomaly score and likelihood, I'd like a checkbox for each. When checked, the line is displayed. Default is checked.

**Comment by jefffohl** [comment]
@rhyolight - how do you feel about the introduction of Angular as a framework for tying together components? I am using it on the nupic.visualizations app. It can make tying together a lot of functionality in the page quite easy.

If you don't want to add a framework, I can work with native JS as well.

**Comment by rhyolight** [comment]
Do it!

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
Would you like to have all of the controls that we have in nupic.visualizations here, or just the toggle for the anomaly series?

**Comment by rhyolight** [comment]
I think just the anomaly lines.
