### ISSUE TITLE
GET /_models is not consistent

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/smartthings.htm.bridge#36]
Sometimes it is:
```javascript
[
    "Vitaly+Workstation_power",
    "Entrance+Hallway+Motion+Sensor_temperature",
    "Mini+Fridge_power"
]
```
and other times we get this:
```javascript
[
   "Entrance+Hallway+Motion+Sensor_temperature", 
   "Vitaly+Workstation_power",
   "Entrance+Hallway+Motion+Sensor_motion",
   "Restroom+Door_acceleration",
   "Restroom+Door_temperature",
   "Dendrite+Door_temperature", 
   "Keurig_power", 
   "Restroom+Door_contact", 
   "Mini+Fridge_power"
]
```

I am assuming that this is not the intended result?

**Comment by rhyolight** [comment]
That's weird...

**Comment by rhyolight** [comment]
The problem was a Heroku configuration problem. I set up 2 dynos for this application, so some requests were going to the 2nd dyno, which is a completely different instance. I've downgraded it to only 1 now. If we need to scale horizontally, just adding dynos obviously won't work.
