### ISSUE TITLE
As a GUI user, I can choose aggregation while looking at the chart

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/smartthings.htm.bridge#46]
Perhaps a dropdown menu like the current limit and since? 

For the user to choose an aggregation, the "since" dropdown must be chosen. This is because the backend database cannot aggregate on the data without a start time. So the aggregation dropdown should be disabled unless the user has chosen a "since" time. 

The options for aggregation should be an integer and a duration (so maybe a dropdown won't work?). Ideally user will input an integer like `3` and choose a duration from the following: seconds, minutes, hours, days, weeks. 

The actual call to the server can just append the aggretation parameter to the URL like this:

    /_data/sensor/power/Mini+Fridge?since=1455042385

Plus 1 hour aggregation:

    /_data/sensor/power/Mini+Fridge?since=1455042385&aggregate=1h

**Comment by rhyolight** [comment]
@jefffohl If you want some work, this would be a good one.

**Comment by jefffohl** [comment]
@rhyolight - What do you think of this kind of UI? See my sketch. Instead of pulldown menus, there would be a slider along the bottom of the graph which allows the user to adjust the aggregate amount, as well as move the window across the dataset. This would require knowing at all times the current size of the time series data set.
![chartui](https://cloud.githubusercontent.com/assets/641147/13063471/532d25d8-d3fd-11e5-8595-d042d0b77d5a.png)

**Comment by rhyolight** [comment]
@jefffohl Because the slider window is a common interface tool for charts, I'm afraid turning its behavior on its head like this would be confusing. Where would the aggregation period be displayed? How will you show to user that the data itself is changing?

**Comment by jefffohl** [comment]
I want to make sure that I understand what is happening with the term "aggregation". My current understanding is that this term means, "the amount of time to display". i.e. 1 hour's worth of data, 1 day's worth of data, 1 week's worth of data, etc.

**Comment by rhyolight** [comment]
I knew we had a miscommunication. :)  I am using the term "aggregation" to
mean reducing the whole amount of data in the stream to a representation of
the actual data. For example, I'm doing a mean over time period. So when I
say "1 hour" aggregated mean, I am taking all the data values within each
hour period and averaging them into an hourly value. So the original data
set, which could have had any number of point in an hour, will now only
have 1 point per hour.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by jefffohl** [comment]
Ah! OK, thanks for the clarification, and sorry that I did not fully grasp it earlier. Sounds like a simple text field followed by a select menu should do the trick. Should be pretty simple to wire up.

**Comment by rhyolight** [comment]
![](http://clipperdata.com/wp-content/uploads/2015/07/I-love-it-when-a-plan-comes-together.jpg)
