### ISSUE TITLE
Plot anomaly likelihood as a bar chart behind other line charts

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/smartthings.htm.bridge#5]
To keep with the "grok" style of anomaly display, the anomaly likelihood might look better as a bar chart displayed on a log scale (#4) behind the other line charts. This bar chart should be somewhat subdued so it does not overpower the value data, but visible enough that spikes in its value are evident visually.

**Comment by rhyolight** [comment]
Here is some code I wrote a few years ago you might be able to reuse: https://github.com/numenta/numenta-apps/blob/master/htm.it/static/js/lib/fog/fog.js#L281-L310

**Comment by jefffohl** [comment]
@rhyolight - I have added this functionality. I added highlights for anomalyLikelihood and anomalyScore both. Let me know what you think. It's a start.

**Comment by rhyolight** [comment]
@jefffohl Thanks. I've been playing catch-up all week. I'll get this thing deployed as soon as I can.
